/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_emmo_ai_nanovg_NanoVG */

#ifndef _Included_org_emmo_ai_nanovg_NanoVG
#define _Included_org_emmo_ai_nanovg_NanoVG
#ifdef __cplusplus
extern "C" {
#endif
#undef org_emmo_ai_nanovg_NanoVG_NVG_ANTIALIAS
#define org_emmo_ai_nanovg_NanoVG_NVG_ANTIALIAS 1L
#undef org_emmo_ai_nanovg_NanoVG_NVG_STENCIL_STROKES
#define org_emmo_ai_nanovg_NanoVG_NVG_STENCIL_STROKES 2L
#undef org_emmo_ai_nanovg_NanoVG_NVG_DEBUG
#define org_emmo_ai_nanovg_NanoVG_NVG_DEBUG 4L
#undef org_emmo_ai_nanovg_NanoVG_NVG_SDF_TEXT
#define org_emmo_ai_nanovg_NanoVG_NVG_SDF_TEXT 128L
#undef org_emmo_ai_nanovg_NanoVG_NVG_SUBPIXEL_TEXT
#define org_emmo_ai_nanovg_NanoVG_NVG_SUBPIXEL_TEXT 256L
#undef org_emmo_ai_nanovg_NanoVG_NVG_MSDF_TEXT
#define org_emmo_ai_nanovg_NanoVG_NVG_MSDF_TEXT 8192L
#undef org_emmo_ai_nanovg_NanoVG_NVG_COLOR_TEXT
#define org_emmo_ai_nanovg_NanoVG_NVG_COLOR_TEXT 16384L
#undef org_emmo_ai_nanovg_NanoVG_NVG_VIRTUAL_ATLAS
#define org_emmo_ai_nanovg_NanoVG_NVG_VIRTUAL_ATLAS 32768L
#undef org_emmo_ai_nanovg_NanoVG_MSDF_MODE_BITMAP
#define org_emmo_ai_nanovg_NanoVG_MSDF_MODE_BITMAP 0L
#undef org_emmo_ai_nanovg_NanoVG_MSDF_MODE_SDF
#define org_emmo_ai_nanovg_NanoVG_MSDF_MODE_SDF 1L
#undef org_emmo_ai_nanovg_NanoVG_MSDF_MODE_MSDF
#define org_emmo_ai_nanovg_NanoVG_MSDF_MODE_MSDF 2L
/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgCreateVk
 * Signature: (JJJJIJJJII)J
 */
JNIEXPORT jlong JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgCreateVk
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong, jint, jint);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgDeleteVk
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgDeleteVk
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgBeginFrame
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgBeginFrame
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgEndFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgEndFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgCreateFont
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgCreateFont
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgFindFont
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgFindFont
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgSetFontMSDF
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgSetFontMSDF
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgFontFace
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgFontFace
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgFontSize
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgFontSize
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgFillColor
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgFillColor
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgText
 * Signature: (JFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgText
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jstring);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgBeginPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgBeginPath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgFill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgFill
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_emmo_ai_nanovg_NanoVG
 * Method:    nvgStroke
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_emmo_ai_nanovg_NanoVG_nvgStroke
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
